"""Render-contract error taxonomy (sanitized public codes)."""

from __future__ import annotations


class RenderContractError(ValueError):
    """Fail-closed render contract error with a stable public code."""

    def __init__(self, code: str, message: str) -> None:
        self.code = code
        self.public_message = message
        super().__init__(message)


REQUEST_INVALID = "REQUEST_INVALID"
OUTPUT_NAME_INVALID = "OUTPUT_NAME_INVALID"
DELIVERY_MODE_INVALID = "DELIVERY_MODE_INVALID"
TEMPLATE_REQUIRED = "TEMPLATE_REQUIRED"
TEMPLATE_NOT_SUPPORTED = "TEMPLATE_NOT_SUPPORTED"
TEMPLATE_IDENTITY_INVALID = "TEMPLATE_IDENTITY_INVALID"
TEMPLATE_DIGEST_MISMATCH = "TEMPLATE_DIGEST_MISMATCH"
TEMPLATE_MEDIA_TYPE_INVALID = "TEMPLATE_MEDIA_TYPE_INVALID"
TEMPLATE_MAGIC_MISMATCH = "TEMPLATE_MAGIC_MISMATCH"
CONTENT_BLOCKS_INVALID = "CONTENT_BLOCKS_INVALID"
INLINE_OUTPUT_TOO_LARGE = "INLINE_OUTPUT_TOO_LARGE"
INLINE_TEMPLATE_TOO_LARGE = "INLINE_TEMPLATE_TOO_LARGE"
ARTIFACT_SINK_UNAVAILABLE = "ARTIFACT_SINK_UNAVAILABLE"
ARTIFACT_CREATE_CONFLICT = "ARTIFACT_CREATE_CONFLICT"
RENDERER_NOT_AVAILABLE = "RENDERER_NOT_AVAILABLE"
FORMAT_NOT_SUPPORTED = "FORMAT_NOT_SUPPORTED"
CANCELLED = "CANCELLED"
TIMEOUT = "TIMEOUT"
INTERNAL_SANITIZED = "INTERNAL_SANITIZED"

HTTP_STATUS = {
    REQUEST_INVALID: 400,
    OUTPUT_NAME_INVALID: 400,
    DELIVERY_MODE_INVALID: 400,
    TEMPLATE_REQUIRED: 400,
    TEMPLATE_NOT_SUPPORTED: 400,
    TEMPLATE_IDENTITY_INVALID: 400,
    TEMPLATE_DIGEST_MISMATCH: 400,
    TEMPLATE_MEDIA_TYPE_INVALID: 400,
    TEMPLATE_MAGIC_MISMATCH: 400,
    CONTENT_BLOCKS_INVALID: 400,
    INLINE_OUTPUT_TOO_LARGE: 400,
    INLINE_TEMPLATE_TOO_LARGE: 400,
    ARTIFACT_SINK_UNAVAILABLE: 503,
    ARTIFACT_CREATE_CONFLICT: 409,
    RENDERER_NOT_AVAILABLE: 501,
    FORMAT_NOT_SUPPORTED: 400,
    CANCELLED: 409,
    TIMEOUT: 504,
    INTERNAL_SANITIZED: 500,
}
